# noqa role-name - this is a meta role that doesn't need a name
---
dependencies:
  - role: container-engine/validate-container-engine
    tags:
      - container-engine
      - validate-container-engine

  - role: container-engine/gvisor
    when:
      - gvisor_enabled
      - container_manager in ['docker', 'containerd']
    tags:
      - container-engine
      - gvisor

  - role: container-engine/containerd
    when:
      - container_manager == 'containerd'
    tags:
      - container-engine
      - containerd
